symbols:
  - BTC
  - ETH
  - BNB
  - DOT
  - ADA
  - BTT
  - MANA
  - REN
  - RUNE
  - ENJ
  - ONE
  - RVN
  - AAVE
  - XLM
  - LINK
  - RAMP
  - CAKE
  - MATIC
  - AVAX
  - SOL
  - 1INCH
  - INJ
  - FTM
  - AR
  - GO

targets:
 - USDT
 - BTC
